// build-types.mjs
// Generates library/src/generated.ts (TypeScript interfaces) from schema/framework-data/*.schema.json,
// so the query library autocompletes every one of the framework's own field names. Run:
//   node tools/build-types.mjs   (also runs automatically as the library's "prebuild")
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_DIR = join(ROOT, "schema", "framework-data");
const OUT = join(ROOT, "library", "src", "generated.ts");

const pascal = (s) =>
  s.replace(/[^A-Za-z0-9]+/g, " ").trim().split(" ").map((w) => w[0].toUpperCase() + w.slice(1)).join("");

function tsType(schema) {
  if (!schema || typeof schema !== "object") return "unknown";
  switch (schema.type) {
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "array": {
      const it = schema.items || {};
      const props = it.properties || {};
      if ("slug" in props) return "Link[]";
      if ("url" in props) return "FileRef[]";
      if (it.type === "string") return "string[]";
      return "unknown[]";
    }
    default:
      return "unknown";
  }
}

const files = readdirSync(SCHEMA_DIR).filter((f) => f.endsWith(".schema.json")).sort();
const entities = [];
const blocks = [];

for (const f of files) {
  const entity = f.replace(/\.schema\.json$/, "");
  const schema = JSON.parse(readFileSync(join(SCHEMA_DIR, f), "utf8"));
  const iface = pascal(entity);
  entities.push({ entity, iface });

  const lines = [`export interface ${iface} extends FrameworkRecord {`, `  $entity: ${JSON.stringify(entity)};`];
  for (const [key, prop] of Object.entries(schema.properties || {})) {
    if (key === "id" || key === "slug") continue; // provided by FrameworkRecord
    lines.push(`  ${JSON.stringify(key)}?: ${tsType(prop)};`);
  }
  lines.push("}");
  blocks.push(lines.join("\n"));
}

const map = entities.map((e) => `  ${JSON.stringify(e.entity)}: ${e.iface};`).join("\n");
const names = entities.map((e) => JSON.stringify(e.entity)).join(", ");

const out = `// AUTO-GENERATED by tools/build-types.mjs from schema/framework-data/*.schema.json.
// Do not edit by hand; run \`node tools/build-types.mjs\` to regenerate.
import type { FrameworkRecord, Link, FileRef } from "./types.js";

${blocks.join("\n\n")}

/** Maps each known dataset name to its record type. */
export interface EntityTypes {
${map}
}

/** The name of any known (typed) dataset. */
export type EntityName = keyof EntityTypes;

/** Every known dataset name, at runtime. */
export const ENTITY_NAMES: EntityName[] = [${names}];
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT} with ${entities.length} entity interfaces.`);
